let log_cm = false    (* classmapper *)
let log_cp = false    (* classpath; bytecode lookup *)
let log_re = false    (* related to regular expressions *)
let log_mm = true    (* method matching *)
let log_ev = false    (* instrumentation to emit events *)
let log_in = true    (* Instrumentation Logging *)
let log_dbg = false   (* category used only during debugging of small parts *)
